export enum Technologies {
    REACT = "React",
    PYTHON = "Python",
    JAVA = "Java",
    JAVASCRIPT = "JavaScript",
    TYPESCRIPT = "TypeScript",
    HTML = "HTML",
    CSS = "CSS",
    NEXTJS = "Next.js",
    NODEJS = "Node.js",
    EXPRESS = "Express",
    MONGODB = "MongoDB",
    POSTGRESQL = "PostgreSQL",
    FLASK = "Flask",
    SPRING = "Spring",
    AWS = "AWS",
    DOCKER = "Docker",
    AZURE = "Azure",
    ELASTICSEARCH = "Elasticsearch",
    KIBANA = "Kibana",
    LOGSTASH = "Logstash",
    REDIS = "Redis",
    KAFKA = "Kafka",
    KOTLIN = "Kotlin",
}
